### ISSUE TITLE
Hi-C input format

### ISSUE THREAD

**Issue by biohubx** [PhanstielLab/BentoBox#24]
Hi,
    I want to use BentoBox to make a heatmap for 2 Hi-C data sets.
    I check out this example data: https://github.com/PhanstielLab/BentoBox/blob/master/data/bb_gmHicData.rda
![image](https://user-images.githubusercontent.com/12387462/109093491-6f7dc080-76e6-11eb-9608-e36eb4e8ced9.png)

   Do you have any suggestions to convert HiC-Pro contact matrix to the input format BentoBox requires?

Best,

**Comment by nekramer** [comment]
I'm not familiar with the HiC-Pro contact matrix format, but as long as the matrix is a 3-column sparse, upper triangular data frame of interaction positions and their counts/signal/freq, BentoBox should be able to read it. Essentially, the start of each interaction bin will be in column 1, the end of each interaction bin will be in column 2, and the measure of that interaction will be in column 3. If that doesn't make sense, a quick glance at the HiC-Pro docs tells me it seems like it should be possible to convert the HiC-Pro interaction products to .hic file format with the hicpro2juicebox.sh utility, and then this file can be directly read into BentoBox. Hope this helps!

**Comment by biohubx** [comment]
thanks a lot. I will try to convert HiC-Pro to .hic format.
