### ISSUE TITLE
Transcript annotation when running documentation code uses UCSC ID

### ISSUE THREAD

**Issue by KeelyDulmage** [PhanstielLab/BentoBox#26]
I followed the example code for bb_plotTranscripts() as found in the documentation:

>library("TxDb.Hsapiens.UCSC.hg19.knownGene")
library("org.Hs.eg.db")
bb_pageCreate(width = 7.5, height = 3.5, default.units = "inches")
bb_plotTranscripts(chrom = "chr8", chromstart = 1000000, chromend = 2000000,
                   assembly = "hg19", labels = "gene",
                   x = 0.5, y = 0.5, width = 6.5, height = 2.5,
                   just = c("left", "top"), default.units = "inches")
bb_plotGenomeLabel(chrom = "chr8", chromstart = 1000000, chromend = 2000000,
                   x = 0.5, y = 3.03, length = 6.5, default.units = "inches")
bb_plotLegend(legend = c("+ strand", "- strand"), fill = c("#669fd9", "#abcc8e"), border = FALSE,
              x = 0.5, y = 1, width = 1, height = 0.5, just = c("left", "top"))
bb_pageGuideHide()

Which works fine enough if you label by gene, but when I enable transcript-level labelling it gives you the UCSC ID, which totally confused me.
![image](https://user-images.githubusercontent.com/11774560/110503905-a8e10380-80ca-11eb-8905-02ce71c05030.png)

In general it is more useful for our purposes if transcripts use Ensembl or Refseq IDs, but if you keep the UCSC ID I would suggest mentioning that in the documentation, I definitely thought it was a bug at first.

**Comment by nekramer** [comment]
Sorry that this wasn't clear! In the past couple months I've been working on adding documentation to detail how to use different transcript IDs with Bioconductor TxDb packages, so hopefully that is helpful for you in switching to your most-used IDs.
