### ISSUE TITLE
how to save the plots

### ISSUE THREAD

**Issue by biohubx** [PhanstielLab/BentoBox#27]
Hi,
    it seems that BentoBox is an interactive package. I ran BentoBox on the longleaf, not RStudio. Do you know how to save the figure? 
Best,

**Comment by nekramer** [comment]
If you use `pdf()` before your BentoBox code (specifying the same dimensions of the page you make with `bb_pageCreate`) and then `dev.off()` after your BentoBox code, you'll save the figure to a pdf. You can similarly do this with other type of image saving functions, but `pdf` is my favorite to use with BentoBox.

**Comment by Simple53** [comment]
I have used pageGuideHide() before `dev.off()`, but still got the grids. How to hide the grids when saving to pdf using `pdf()` and `dev.off()`?

**Comment by jpflores-13** [comment]
Hello!

Alternatively, you can use the `showGuides` argument in the `pageCreate()` function and set it to `FALSE` once everything is plotted correctly.

**Comment by Simple53** [comment]
It works！Thank you. @jpflores-13
