### ISSUE TITLE
bb_plotGenes rendering issue

### ISSUE THREAD

**Issue by mdozmorov** [PhanstielLab/BentoBox#28]
Hi. Thanks for the great package! When running the tutorial code from README, there's a strange phenomenon - plotting `bb_plotGenes()` is delayed, and sometimes hides some parts. This is best seen on the screen capture. It happens when running the code line-by-line, but at the end, the image looks like it should. It is a minor issue, but I thought to mention that something may not be right.

https://user-images.githubusercontent.com/864945/111831155-57542800-88c5-11eb-8de5-d4589e09778e.mp4

**Comment by nekramer** [comment]
Unfortunately, this is an aspect of the R graphics device window that we can't entirely control or speed up. Depending on your system, as you add more BentoBox plots to a layout R may take a bit longer in actually load and render them to the graphics window. Internally, the code is running as it should and plotting in the proper order, but R takes a little while to catch up!
