### ISSUE TITLE
quiet=FALSE / TRUE

### ISSUE THREAD

**Issue by mikelove** [PhanstielLab/BentoBox#30]
The `bb_*` functions print messages, but I may suggest `quiet=FALSE` arguments with the paradigm:

```
if (!quiet) message(...)
```

Then developers who want to run BentoBox inside their functions can avoid lots of `suppressMessages()` calls (or just turn those into `quiet=TRUE` in the function call).

**Comment by nekramer** [comment]
thank you for this suggestion!
